layout_spectrum: 0.9595745
color:
  saturation: 0.002445489
  lightness: 0.4688726
  brandStrength: 0.834984
  rhythmicContrast: 0.4661379
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.3092725
name: Skyes
