color:
  saturation: 0
  brandStrength: 0.4851064
  rhythmicContrast: 0.4661379
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  lightness: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.9595745
typography_spectrum: 0.7127659
name: Skyes
